version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    depends_on:
      - db
    env_file:
      - .env.dev   
    ports:
      - "5050:80"
    networks:
      - my_network

  minio:  
    image: minio/minio:latest
    container_name: my_minio
    env_file:
      - .env.dev
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - my_network

  web:
    build:
      context: ./chat_project
      dockerfile: Dockerfile
    container_name: my_django
    env_file:
      - .env.dev
    command: gunicorn chat_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./chat_project:/app
    depends_on:
      - db
      - minio  # 👈 добавил minio как зависимость
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:
  minio_data:  

networks:
  my_network:
    driver: bridge
